package kr.flooding.backend.domain.user.enums

enum class Department(
	name: String,
) {
	EDUCATION_PLANNING_DEPARTMENT("교육기획부"),
	EDUCATION_RESEARCH_DEPARTMENT("교육연구부"),
	CURRICULUM_MANAGEMENT_DEPARTMENT("교육과정운영부"),
	AFTER_SCHOOL_EDUCTION_DEPARTMENT("창체방과후교육부"),
	STUDENT_LIFE_SAFE_DEPARTMENT("학생생활안전부"),
	MEISTER_DEPARTMENT("마이스터부"),
	EMPLOYMENT_CAREER_DEPARTMENT("취업진로교육부"),
	PROFESSIONAL_EDUCTION_DEPARTMENT("전문교육부"),
	FIRST_GRADE_DEPARTMENT("1학년부"),
	SECOND_GRADE_DEPARTMENT("2학년부"),
	THIRD_GRADE_DEPARTMENT("3학년부"),
}
