version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/flooding-backend

permissions:
  - object: /home/ubuntu/flooding-backend
    owner: ubuntu
    group: ubuntu

hooks:

  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      runas: root

  ApplicationStart:
    - location: scripts/start.sh
      runas: root
