spring:
  jpa:
    hibernate:
      ddl-auto: update

client:
  verify-url: "https://flooding.kr/signup/auth/verify"
  reset-password-url: "https://flooding.kr/signin/resetpassword"
  invite-club-url: "https://flooding.kr/club/invite"

jwt:
    access-token-expires: 900000        # 15분
    refresh-token-expires: 1209600000   # 14일
